# Generated by Django 5.0 on 2023-12-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_extrauser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='extrauser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extrauser'),
        ),
    ]
