# Generated by Django 5.0 on 2023-12-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
    ]
