# Generated by Django 5.0 on 2023-12-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(max_length=600),
        ),
    ]
